name: Build and Release EXE

on:
  push:
    tags:
      - 'v*' 

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write 
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller requests

      - name: Build EXE
        run: python -m PyInstaller --onefile --windowed video_downloader.py

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/video_downloader.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}