name: CI - Type Check, Lint, Format

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  check:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.in-project true
          poetry install --no-root --no-interaction

      - name: Run MyPy type checking
        shell: powershell
        run: |
          cd ${{ github.workspace }}
          poetry run mypy src

      - name: Run Pylint analysis
        shell: powershell
        run: |
          cd ${{ github.workspace }}
          poetry run pylint src

      - name: Run Black formatting check
        shell: powershell
        run: |
          cd ${{ github.workspace }}
          poetry run black --check src
